name: bookworms_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  archive: ^4.0.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  collection: ^1.19.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.3
  flutter_slidable: ^4.0.0
  flutter_sticky_header: ^0.7.0
  flutter_svg: ^2.0.17
  http: ^1.3.0
  image_network: ^2.6.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  shared_preferences: ^2.0.8
  showcaseview: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  timeago: ^3.2.2
  url_launcher: ^6.3.1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.7
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
      - 'assets/images/'
