name: bookworms_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  http: ^1.2.2
  archive: ^3.0.0 
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.25.7
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
